package entity;// default package
// Generated 2015-12-5 12:46:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Collection generated by hbm2java
 */
public class Collection implements java.io.Serializable {

	private int id;
	private Message message;
	private UserDetail user;
	private Date time;
	
	
	
	public Collection() {
		
	}
	
	public Collection(UserDetail user, Message message, Date time) {
		super();
		this.message = message;
		this.user = user;
		this.time = time;
	}

	public Collection(int id, Message message, UserDetail user, Date time) {
		super();
		this.id = id;
		this.message = message;
		this.user = user;
		this.time = time;
	}

	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Message getMessage() {
		return message;
	}
	public void setMessage(Message message) {
		this.message = message;
	}
	public UserDetail getUser() {
		return user;
	}
	public void setUser(UserDetail user) {
		this.user = user;
	}
	public Date getTime() {
		return time;
	}
	public void setTime(Date time) {
		this.time = time;
	}
	
	

	

}
