package entity;// default package
// Generated 2015-12-5 12:46:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	//普通属性
	private int messageId;
	private Date time;
	private String content;
	private int isDelete;
	private String image;
	private Integer approve;
	private Integer oppose;
	private String title;
	private String userName;
	//多对一属性
	private UserDetail user;
	private Category category;
	//一对多属性
	private Set<Comment>comments = new HashSet<Comment>();
	private Set<Collection>collections = new HashSet<Collection>();
	public Message() {
	}

	public Message(int messageId, Date time, int isDelete, Category category) {
		this.messageId = messageId;
		this.time = time;
		this.isDelete = isDelete;
		this.category = category;
	}

	public Message(int messageId, UserDetail user, Date time, String content, Category category,int isDelete,  String image,
			Integer approve, Integer oppose) {
		this.messageId = messageId;
		this.user = user;
		this.time = time;
		this.content = content;
		this.isDelete = isDelete;
		this.category = category;
		this.image = image;
		this.approve = approve;
		this.oppose = oppose;
	}

	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(int isDelete) {
		this.isDelete = isDelete;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Integer getApprove() {
		return this.approve;
	}

	public void setApprove(Integer approve) {
		this.approve = approve;
	}

	public Integer getOppose() {
		return this.oppose;
	}

	public void setOppose(Integer oppose) {
		this.oppose = oppose;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public UserDetail getUser() {
		return user;
	}

	public void setUser(UserDetail user) {
		this.user = user;
	}

	public Set<Comment> getComments() {
		return comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	public Set<Collection> getCollections() {
		return collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
