package entity;// default package

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

// Generated 2015-12-5 12:46:46 by Hibernate Tools 3.4.0.CR1

/**
 * UserDetail generated by hbm2java
 */
public class UserDetail implements java.io.Serializable {

	@Expose
	private int userId;
	@Expose
	private String minor;
	@Expose
	private String major;
	@Expose
	private int grade;
	@Expose
	private String name;
	@Expose
	private String signature;
	@Expose
	private int gender;
	@Expose
	private String image;

	private Set<Message> messages = new HashSet<Message>();
	private Set<Comment> comments = new HashSet<Comment>();
	private Set<Collection> collections = new HashSet<Collection>();

	public UserDetail() {
	}

	public UserDetail(int userId, String name) {
		this.userId = userId;
		this.name = name;
	}

	public UserDetail(int userId, String minor, String major, Integer grade, String name, String signature,
			int gender, String image) {
		this.userId = userId;
		this.minor = minor;
		this.major = major;
		this.grade = grade;
		this.name = name;
		this.signature = signature;
		this.gender = gender;
		this.image = image;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getMinor() {
		return this.minor;
	}

	public void setMinor(String minor) {
		this.minor = minor;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public int getGender() {
		return this.gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set<Message> getMessages() {
		return messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	public Set<Comment> getComments() {
		return comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	public Set<Collection> getCollections() {
		return collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

	@Override
	public String toString() {
		return "UserDetail [userId=" + userId + ", minor=" + minor + ", major=" + major + ", grade=" + grade + ", name="
				+ name + ", signature=" + signature + ", gender=" + gender + ", image=" + image + ", messages="
				+ messages + ", comments=" + comments + ", collections=" + collections + "]";
	}

}
