package entity;// default package
// Generated 2015-12-5 12:46:46 by Hibernate Tools 3.4.0.CR1

/**
 * UserValidate generated by hbm2java
 */
public class UserValidate implements java.io.Serializable {

	private int userSecurityId;
	private String name;
	private String salt;
	private String password;
	private String email;
	public int getUserSecurityId() {
		return userSecurityId;
	}
	public void setUserSecurityId(int userSecurityId) {
		this.userSecurityId = userSecurityId;
	}
	public String getSalt() {
		return salt;
	}
	public void setSalt(String salt) {
		this.salt = salt;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	@Override
	public String toString() {
		return "UserValidate [userSecurityId=" + userSecurityId + ", name=" + name + ", salt=" + salt + ", password="
				+ password + ", email=" + email + "]";
	}

	

}
